version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: ujax-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ujax
      MYSQL_USER: ujax_user
      MYSQL_PASSWORD: ujax1234
      TZ: Asia/Seoul
    volumes:
      - mysql-data:/var/lib/mysql
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci

  redis:
    image: redis:latest
    container_name: ujax_redis
    ports:
      - "6379:6379"
    restart: always

volumes:
  mysql-data: