spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:mysql://${RDS_ENDPOINT:localhost}:3306/ujax?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&useSSL=false&rewriteBatchedStatements=true
    username: ujax_user
    password: ${RDS_PASSWORD:ujax1234}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 32

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

  flyway:
    enabled: false

